# .pre-commit-config.yaml
repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  # Terraform specific hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt # Formats your Terraform code
        args:
          - --args=-recursive # Ensures formatting is applied to subdirectories

      - id: terraform_validate # Validates your Terraform configuration
        # You can add arguments if needed, e.g., to specify variable files
        # args:
        #   - --args=-var-file=dev.tfvars
        #   - --args=-var-file=prod.tfvars

      #- id: terraform_docs # Generates or updates documentation (e.g., README)
      #  args:
      #    - --hook-config=--path-to-file=README.md # Default path
          # - --hook-config=--add-to-existing-file=true # If you have existing content
          # - --hook-config=--create-file-if-not-exist=true

      - id: terraform_tflint # Lints your Terraform code for errors and best practices
        # Ensure tflint is installed and configured separately if needed (e.g., with a .tflint.hcl file)

      - id: terraform_trivy # Scans for security vulnerabilities (tfsec is now part of Trivy)
        # Consider using Trivy directly or another security scanner hook if tfsec gives deprecation warnings.
        # As of recent updates, tfsec has been integrated into Trivy.
        # You might find a hook like `terraform_trivy` in the same repository or need to configure a Trivy hook separately.

      # - id: terraform_trivy # Alternative for security scanning using Trivy
      #   args:
      #     - '--args=--security-checks=vuln,config'

      - id: terraform_checkov # Scans for infrastructure-as-code misconfigurations
        # args:
          # - --args=--framework terraform # Specify framework if needed
          # - --args=--quiet # To reduce verbosity
        # Ensure Checkov is installed if you use this hook

  # You can add other repositories and hooks as needed
  # For example, for Terragrunt:
  # - repo: https://github.com/gruntwork-io/pre-commit
  #   rev: v0.1.23 # Check for latest version
  #   hooks:
  #     - id: terragrunt-hclfmt
